@startuml

[*] -> TurnedOff : Start
TurnedOff --> TurnedOn : Turn On
TurnedOn --> TurnedOff : Turn Off

TurnedOn --> Driving   : Drive
Driving -> Driving  : Accelerate
Driving <-- Driving  : Break
Driving --> TurnedOn  : Park

TurnedOff -> [*] : Finish
@enduml
