---
name: 'Tests'

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  prove:
    uses: josegomezr/perl-toolkit/.github/workflows/perl-prove.yml@c75826587cddf7ec456da4621b44b3392f6dff0c
    name: "Prove"
    with:
      prove-args: '--rc=.proverc.gha'
