---
name: 'Perl Lint Checks'

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  perl-lint-checks:
    runs-on: ubuntu-latest
    name: "Perltidy"
    container:
      image: perldocker/perl-tester:5.26
    steps:
      - uses: actions/checkout@v4
      - run: GITHUB_ACTIONS=1 tidyall --check-only --all --quiet
  perl-critic-checks:
    runs-on: ubuntu-latest
    name: "Perlcritic"
    container:
      image: perldocker/perl-tester:5.26
    steps:
      - uses: actions/checkout@v4
      - run: perlcritic --quiet .
