---
name: 'Tests'

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  prove:
    uses: josegomezr/perl-toolkit/.github/workflows/perl-prove.yml@c76659389627dc9b89fa7bf6c48d5c90da97cc90
    name: "Prove"
    with:
      prove-args: '--rc=.proverc.gha'
