---
name: 'Tests'

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  prove:
    uses: josegomezr/perl-toolkit/perl-prove.yml@test_shortcut
    name: "Prove"
    with:
      prove-args: '--rc=.proverc.gha'
