---
name: 'Linters'

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  perl-lint-checks:
    uses: josegomezr/perl-toolkit/.github/workflows/perl-tidyall.yml@main
    name: "Perltidy"

  perl-critic-checks:
    uses: josegomezr/perl-toolkit/.github/workflows/perl-critic.yml@main
    name: "Perlcritic"
