---
name: 'Tests'

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  perl-prove:
    runs-on: ubuntu-latest
    name: "Prove"
    container:
      image: perldocker/perl-tester:5.26
    steps:
      - uses: actions/checkout@v4
      - run: PERL5LIB=$PWD/t/lib/:$PERL5LIB prove --formatter TAP::Formatter::GitHubAction
