---
name: 'Tests'

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  perl-prove:
    runs-on: ubuntu-latest
    name: "Prove"
    container:
      image: registry.opensuse.org/home/josegomezr/devel/openqa/ci/containers-tw/base-perl:latest
    steps:
      - uses: actions/checkout@v4
      - run: PERL5LIB=$PWD/t/lib/:$PERL5LIB prove --formatter TAP::Formatter::GitHubAction
